### ISSUE TITLE
Request for Command: Need global fixship to all non static grids.

### ISSUE THREAD

**Issue by dorimanx** [LordTylus/SE-Torch-Plugin-ALE-ShipFixer#3]
Hi,
I like to request to add emergency server wide fixship command to all non static grids..
WHY: sometimes something is really stuck at random ships and draining SIM non stop till player/admin finds this grid, and do fixship on it, and in few seconds no more sim drain, till it's happens to other grid, wonders of keen code.

So to have a tool for emergency server fix, only for admin, command like !fixshipmod allships
What it's should do:
1.Stop all ships.
2.Eject all players from seats in all ships.
3.cut / paste ship

do this in batch of 5 till all done.

I know it's a massive lag and all that, but, this maybe the last hope for finding this 1 ship that has no other sign of any kind, that draining 0.3 global sim.

Thank you.

**Comment by LordTylus** [comment]
As this is on the bottom of my todo list. I think I should ask if its still needed?

**Comment by dorimanx** [comment]
it's needed. and i think i will do such command later :)

**Comment by dorimanx** [comment]
but after short thinking with my team, it's seems that we didnt had need for this for long time now since some game updates.
So lets close this request.
